# Generated by Django 4.1.2 on 2022-12-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_paymentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('Contactno', models.IntegerField()),
                ('Country', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ContactSection',
            },
        ),
    ]
