# Generated by Django 4.1.2 on 2022-12-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_contactsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSection',
        ),
    ]
