# Generated by Django 4.1.2 on 2022-12-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
            ],
            options={
                'db_table': 'Carausal',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
