# Generated by Django 4.1.2 on 2022-12-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_carausal_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carausal',
        ),
    ]
